# Generated by Django 5.0.3 on 2024-04-09 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizeapp', '0004_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progression',
            name='date',
            field=models.DateField(),
        ),
    ]
