# Generated by Django 5.0.3 on 2024-04-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizeapp', '0005_session_rating_alter_personalrecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorizeapp.session'),
        ),
    ]
