# Generated by Django 5.0.3 on 2024-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizeapp', '0011_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_progress',
            field=models.BooleanField(default=True),
        ),
    ]
