# Generated by Django 5.0.3 on 2024-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizeapp', '0012_usersettings_show_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pics/fitness_img.png', null=True, upload_to='profile_pics/'),
        ),
    ]
